version: "3"
services: 
  app: 
    image: tangladum:latest
    ports: 
    - 5000:5000
    volumes:
    - ./src:/app
    depends_on: 
    - db
  db:
    image: postgres:12.3-alpine
    environment: 
      POSTGRES_PASSWORD: "admin"
    volumes:
    - /tmp/pgdata:/var/lib/postgresql/data
